services:
  db:
    image: mysql:8.0
    container_name: lab-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: labdatabase
      MYSQL_USER: labdatabase
      MYSQL_PASSWORD: lab@Database2025
    ports:
      - "3306:3306" # se sua máquina já usa 3306, troque para "3307:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: lab-adminer
    ports:
      - "8080:8080"
environment:
  - MYSQL_ROOT_PASSWORD=...
  - MYSQL_DATABASE=labdatabase
  - MYSQL_USER=labdatabase
  - MYSQL_PASSWORD=lab@Database2025
  - LANG=C.UTF-8
  - LC_ALL=C.UTF-8
command: [ "--character-set-server=utf8mb4", "--collation-server=utf8mb4_0900_ai_ci" ]
